openapi: 3.0.3
info:
  title: Swagger ASDs Application Manager
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
tags:
  - name: Application Manager
    description: Operations about Application Manager
paths:
  /app:
    post:
      tags:
        - Application Manager
      summary: Add a new application to the system
      description: Add a new application to the system
      operationId: addApp
      requestBody:
        description: Create a new application in the system
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
          application/xml:
            schema:
              $ref: '#/components/schemas/App'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/App'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'          
            application/xml:
              schema:
                $ref: '#/components/schemas/App'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:apps
            - read:apps
            
  /app/{appID}:
    get:
      tags:
        - Application Manager
      summary: Get application info by appID
      description: Get application info by appID
      operationId: getApp
      parameters:
        - name: appID
          in: path
          description: ID of application to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - write:apps
            - read:apps
    
    delete:
      tags:
        - Application Manager
      summary: Deletes an application
      description: delete an application
      operationId: deleteApp
      parameters:
        - name: appID
          in: path
          description: App id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid app value
      security:
        - petstore_auth:
            - write:apps
            - read:apps
            
  /app/{userID}:
    get:
      tags:
        - Application Manager
      summary: Get application info by userID
      description: Get application info by userID
      operationId: getAppByUserID
      parameters:
        - name: userID
          in: path
          description: ID of user to return apps
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - write:apps
            - read:apps
  
  /app/status/{appID}:
    get:
      tags:
        - Application Manager
      summary: Get application status by appID
      description: Get application status by appID
      operationId: getAppStatus
      parameters:
        - name: appID
          in: path
          description: ID of application status to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/App'
        '400':
          description: Invalid status value
      security:
        - petstore_auth:
            - write:apps
            - read:apps
  
  /app/backup:          
    post:
        tags:
          - Application Manager
        summary: Create a backup of application
        description: Create a backup of application
        operationId: createBackup
        requestBody:
          description: Create a backup of application
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'
            application/xml:
              schema:
                $ref: '#/components/schemas/App'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/App'
          required: true
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/App'          
              application/xml:
                schema:
                  $ref: '#/components/schemas/App'
          '400':
            description: Invalid input
          '422':
            description: Validation exception
        security:
          - petstore_auth:
              - write:apps
              - read:apps
           
  /app/autobackup/{appID}/{timeInterval}:
    put:
      tags:
        - Application Manager
      summary: Update an autobackup timeinterval
      description: Update an autobackup timeinterval
      operationId: updateAppAutoBackup
      parameters:
        - name: appID
          in: path
          description: ID of application status to return
          required: true
          schema:
            type: integer
            format: int64
        - name: timeInterval
          in: path
          description: Timeinterval for interval
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update an interval timeinterval
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/App'
          application/xml:
            schema:
              $ref: '#/components/schemas/App'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/App'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/App'          
            application/xml:
              schema:
                $ref: '#/components/schemas/App'
        '400':
          description: Invalid ID supplied
        '404':
          description: App not found
        '422':
          description: Validation exception
      security:
        - petstore_auth:
            - write:apps
            - read:apps
            
components:
  schemas:
    App:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: theApp
        description:
          type: string
          example: HSEApp
        currentVersion:
          type: string
          example: '1.3.2'
        status:
          type: string
          example: 'active'
      xml:
        name: app

  requestBodies:
    App:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/App'
        application/xml:
          schema:
            $ref: '#/components/schemas/App'
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/App'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:apps: modify apps in your account
            read:apps: read your apps
    api_key:
      type: apiKey
      name: api_key
      in: header