openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
paths:
  /version/restoreVersion:
    put:
      tags:
        - version_manager
      operationId: addPet
      parameters:
        - name: versionId
          in: query
          description: The id of Version
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /version/selectVersion:
    get:
      tags:
        - version_manager
      operationId: findPetsByStatus
      parameters:
        - name: versionId
          in: query
          description: The id of Version
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
  /version/deleteVersion:
    delete:
      tags:
        - version_manager
      parameters:
        - name: versionId
          in: query
          description: The id of Version
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
  /version/getAllVersionsOfApp:
    get:
      tags:
        - version_manager
      parameters:
        - name: appId
          in: query
          description: The id of Version
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
