openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Kubernetes Manager
    description: Managing kubernetes
paths:
  /kubernetes_manager/change_backup_policies:
    put:
      tags:
        - Kubernetes Manager
      summary: Update an existing backup policy
      description: Update an existing backup policy
      operationId: updatePolicy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BackupPolicy'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BackupPolicy'
        '422':
          description: Validation exception
  /kubernetes_manager/set_kubernetes_settings:
    put:
      tags:
        - Kubernetes Manager
      summary: Update kubernetes settings
      description:  Change the configuration of kubernetes cluster
      operationId: setSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/KubernetesSettings'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KubernetesSettings'
        '422':
          description: Validation exception
  /kubernetes_manager/check_kubernetes_status:
    get:
      tags:
        - Kubernetes Manager
      summary: Check state of kubernetes
      description: Check whether kubernetes is alive and functioning as expected
      operationId: checkStatus
      responses:
        '200':
          description: Kubernetes is alive and works as expected
        '404':
          description: Kubernetes not configured
        '505':
          description: Kubernetes is dead or is not working as expected
components:
  schemas:
    BackupPolicy:
      type: object
      properties:
        backup_regularity:
          type: integer
          format: uint64
          example: 3600
    KubernetesSettings:
      type: object
      properties:
        pods_amount:
          type: integer
          format: uint64
          example: 10
